import React from 'react';

import { firebaseAuth, firebaseStore, firebaseStrg } from '../../../firebaseConfig';
import { getDownloadURL, listAll, ref, uploadString } from 'firebase/storage';
import { setDoc, doc, getDoc, updateDoc, getDocs, collection } from 'firebase/firestore';
import { v4 as uuidv4 } from 'uuid';

const userAuth = firebaseAuth;

/**
 * Get Current User Info in Document
 */
export const setInitUserInfo = async () => {
    if(userAuth.currentUser) {
        try {
            await setDoc(doc(firebaseStore,'userInfo',userAuth.currentUser.email), {
                uid : userAuth.currentUser.uid,
                email : userAuth.currentUser.email,
                emailVerified : userAuth.currentUser.emailVerified,
                displayName : userAuth.currentUser.displayName,
                photoURL : userAuth.currentUser.photoURL,
            }, { merge : true})
        } catch(error) {
            console.log("InitUserInfo Error : ",error)
        }
        
    } else {
        console.log("Not Logined")
    }
}

/**
 * Get All User List In Document
 * @return result - true or false depending on whether the request succeeds or not
 * @return value - Array of User List
 */
export const getAllUserInDoc = async()=> {
    let userList = []
    try {
        await getDocs(collection(firebaseStore,"userInfo"))
            .then((response)=> {
                response.forEach((docs)=> {
                    {docs.data().email !== userAuth.currentUser.email 
                        && userList.push(docs.data())}  
                })
            })
        console.log(userList)
        return { result : true, value : userList}
        
    } catch(error) {
        return {result :false, value : []}
    }
}

export const getUserInfo = async(email: string) => {
    const docRef = doc(firebaseStore,'userInfo',email);
    try {
        const result = await getDoc(docRef);
        return result.data()
    } catch(error) {
        console.log(error)
    }
}
/**
 * Upload Image File's String Value to Firebase Storage
 * @param fileString upload Image File generated by `FileReader()`
 * @return `Object` result : boolean, value : optional
 */
export const uploadPhotoToStrg = async(fileString : string) => {
    const storageRef = ref(firebaseStrg,`userInfo/${userAuth.currentUser.email}/photoURL`);
    try {
        await uploadString(storageRef,fileString,"data_url")    
        return {result : true, value : storageRef}
    } catch(error) {
        console.log(error)
        return {result : false, value : null}
    } 
}

export const updatePhotoURL = async(url : string)=> {
    const docRef = doc(firebaseStore,'userInfo',userAuth.currentUser.email);
    try {
        await updateDoc(docRef, { photoURL : url });
        return true;
    } catch(error) {
        return false;
    } 
}

export const getUserListInStrg = async()=> {
    const storageRef = ref(firebaseStrg, 'userInfo');    
    let userList = []
    try {
        await listAll(storageRef)
            .then((response)=> {
                response.prefixes.map((item : any)=> {
                    const mailString = item._location.path_.split('/')[1];
                    userList.push(mailString);
                })
            })
        return { result : true, value : userList }
    } catch(error){
        return { result : false, value : null}
    }
}
export const getUserInfoInStrg = async(email : string)=> {
    const storageRef = ref(firebaseStrg,`userInfo/${email}/photoURL`)
    try {
        const downURL = await getDownloadURL(storageRef)
        return {result : true, value : downURL}
    } catch(error) {
        return {result : false, value : ""}
    }
    
}

/**
 * Send a friend request to the selected user
 * @param {string} email Who will receive friend requests
 * @return result : boolean, value : message
 */
export const setRequestAddFriendInDoc = async(email : string) => {
    try {
        await setDoc(doc(firebaseStore,'friendReq', `${uuidv4()}`), {
            from : userAuth.currentUser.email,
            to : email,
            checkYn : false,
            status : "request",
            req_date : new Date(),
        })
        return { result : true, value : "Request Success"}
    } catch (error) {
        return { result : false, value : `Error : ${error}`}
    }
}
/**
 * View the full list of friend add requests
 * 
 * Note : View the full list for reuse in other components. 
 * @returns result : `Boolean`, value : `Array` of request List
 */
export const getReuestAddFriendInDoc = async()=> {
    let docList = []
    try {
        await getDocs(collection(firebaseStore,'friendReq'))
            .then((response)=> {
                response.forEach((doc)=>
                    docList.push(doc.data())
                )
            })
            return {result : true, value : docList}
    }catch (error) {
        console.log(`Error : ${error}`)
        return {result : false, value : []};
    }
}